# Generated by Django 6.0.6 on 2026-06-15 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_cities_state_alter_userprofile_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.states'),
        ),
    ]
