# Generated by Django 6.0.6 on 2026-06-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_cities_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobbies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='hobbies',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hobbies',
            field=models.ManyToManyField(blank=True, to='users.hobbies'),
        ),
    ]
