# Generated by Django 6.0.6 on 2026-06-17 11:06

from django.db import migrations, models


def empty_email_to_null(apps, schema_editor):
    UserProfile = apps.get_model('users', 'UserProfile')
    UserProfile.objects.filter(email='').update(email=None)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_created_at'),
    ]

    operations = [
        # Step 1: allow NULL (no unique yet — avoids collision on rebuild)
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        # Step 2: convert every '' to NULL now that the column allows it
        migrations.RunPython(empty_email_to_null, migrations.RunPython.noop),
        # Step 3: add the unique constraint now that there are no duplicate blanks
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
